package klassen.utils.database
import klassen.*

open class Haus(
    immoId: Int = 0,
    objektNr: String = "",
    immoObjektArt: ObjektArt,
    bauJahr: String = "",
    gesamtFlaeche: Double = 0.0,
    preisNetto: Double = 0.0,
    geldTyp: Waehrung,
    provision: Double = 0.0,
    steuer: Int = 19,
    typ: ImmoTyp,
    art: ImmoArt,
    dachTyp: Dach,
    heizungsTyp: Heizung,
    eAusweis: EnergieAusweis,
    energierWert: String = "",
    abwasser: String = "",
    frei: String = "",
    ort: String = "",
    kreis: String = "",
    bundesland: BlandAbk,
    region: Land = Land.Deutschland,
    linkExpose: String = "",
    linkImages: String = "",
    objektTyp: String = "Haus",
    objektTitel: String = "",
    objektText: String = "",

    var hausTyp: String = "",
    var renovierung: String = "",
    var zimmer: String = "",
    var raumHoehe: String = "",
    var lageImHaus: String = "",
    var bad: String = "",
    var kueche: String = "",
    var keller: String = "",
    var heizungsArt: String = "",
    var garten: String = "",
    var stellPlatz: String = "",
    var nettoMieteKaltWohnen: Double = 0.0,
    var nettoMieteKaltGewerbe: Double = 0.0,
    var nettoMieteIstJahr: Double = 0.0,
    var nettoMieteSollJahr: Double = 0.0,


    ): Immo(
    immoId,
    objektNr,
    immoObjektArt,
    bauJahr,
    gesamtFlaeche,
    preisNetto,
    geldTyp,
    provision,
    steuer,
    typ,
    art,
    dachTyp,
    heizungsTyp,
    eAusweis,
    energierWert,
    abwasser,
    frei,
    ort,
    kreis,
    bundesland,
    region,
    linkExpose,
    linkImages,
    objektTyp,
    objektTitel,
    objektText,
    ) {
}