package klassen

open class Whg(
    immoId: Int = 0,
    objektNr: String = "",
    immoObjektArt: ObjektArt,
    bauJahr: String = "",
    gesamtFlaeche: Double = 0.0,
    preisNetto: Double = 0.0,
    geldTyp: Waehrung,
    provision: Double = 0.0,
    steuer: Int = 19,
    typ: ImmoTyp,
    art: ImmoArt,
    dachTyp: Dach,
    heizungsTyp: Heizung,
    eAusweis: EnergieAusweis,
    energierWert: String = "",
    abwasser: String = "",
    frei: String = "",
    ort: String = "",
    kreis: String = "",
    bundesland: BlandAbk,
    region: Land,
    linkExpose: String = "",
    linkImages: String = "",

    var objektTyp: String = "Wohnung",
    var renovierung: String = "",
    var zimmer: String = "",
    var raumHoehe: String = "",
    var lageImHaus: String = "",
    var bad: String = "",
    var heizungsArt: String = "",
    var garten: String = "",
    var stellplatz: String = "",
    var wohnGeld: String = "",
    var wohnflaeche: String = "",
    var nutzFlaeche: String = "",
    var miete: Double = 0.0,
    var nebenKosten: Double = 0.0,
    var stellplatzPreis: Double = 0.0,
    var kaution: Double = 0.0,

    ): Immo(
    immoId,
    objektNr,
    immoObjektArt,
    bauJahr,
    gesamtFlaeche,
    preisNetto,
    geldTyp,
    provision,
    steuer,
    typ,
    art,
    dachTyp,
    heizungsTyp,
    eAusweis,
    energierWert,
    abwasser,
    frei,
    ort,
    kreis,
    bundesland,
    region,
    linkExpose,
    linkImages,) {
}